version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flight_server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - mongodb

volumes:
  mongodb_data:
